default: &default
  encoding: unicode
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  port: 5432
  host: postgres
  timeout: 5000

production:
  <<: *default
  username: postgres
  password: postgres
  database: meritmoney
 
development:
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000  
  database: db/development.sqlite3
