default: &default
  encoding: unicode
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  port: 5432
  host: postgres
  timeout: 5000

production:
  <<: *default
  username: postgres
  password: postgres
  database: meritmoney

development:
  <<: *default
  username: postgres
  password: postgres
  database: meritmoney

